import { initializeApp } from "firebase/app";
import {
  getFirestore,
  collection,
  doc,
  setDoc,
  writeBatch,
} from "firebase/firestore";

// Configuration from .env
const firebaseConfig = {
  apiKey: "AIzaSyA7ZiqaXNgZWPHtLfjAXjpeQySipof-em8",
  authDomain: "foodflow-85210.firebaseapp.com",
  projectId: "foodflow-85210",
  storageBucket: "foodflow-85210.firebasestorage.app",
  messagingSenderId: "503744924224",
  appId: "1:503744924224:web:e8bfe3de2bebfc3dd4ada5",
};

const app = initializeApp(firebaseConfig);
const db = getFirestore(app);

// Helper to get image path
const getImg = (id) => `/images/restaurant${id}.webp`;

const restaurants = [
  {
    id: 1,
    name: "Burger & Bliss",
    rating: 4.8,
    reviews: "1.2k",
    deliveryTime: "25-35 min",
    minOrder: 3500,
    image: getImg(1),
    categories: ["Burgers", "Fast Food", "Snacks"],
    city: "Lagos",
    address: "12 Admiralty Way, Lekki Phase 1",
    openingHours: "10:00 AM - 11:00 PM",
    about: "The juiciest gourmet burgers in Lagos.",
    tags: ["Halal", "Outdoor Seating", "Free Wifi"],
    menu: [
      {
        id: 102,
        name: "BBQ Bacon Burger",
        price: 5500,
        description: "Smoked bacon, BBQ sauce",
        image: getImg(1),
        category: "Mains",
      },
    ],
  },
  {
    id: 2,
    name: "Native Fisherman Soup",
    rating: 4.9,
    reviews: "950",
    deliveryTime: "30-45 min",
    minOrder: 5000,
    image: getImg(2),
    categories: ["Soup", "Swallow", "Seafood", "African"],
    city: "Port Harcourt",
    address: "GRA Phase 2, Port Harcourt",
    openingHours: "11:00 AM - 10:00 PM",
    about: "Authentic Rivers State cuisine prepared by native chefs.",
    tags: ["Nationwide Delivery", "Fresh Catch", "Spicy"],
    menu: [
      {
        id: 201,
        name: "Fisherman Soup",
        price: 8000,
        description: "Fresh seafood soup native to Rivers",
        image: getImg(2),
        category: "Soups",
      },
    ],
  },
  {
    id: 3,
    name: "Grill House",
    rating: 4.6,
    reviews: "2.1k",
    deliveryTime: "20-30 min",
    minOrder: 9000,
    image: getImg(3),
    categories: ["Grills", "Suya", "Chicken"],
    city: "Abuja",
    address: "Wuse 2, Abuja",
    openingHours: "12:00 PM - 11:00 PM",
    about: "The best suya spot in the capital.",
    tags: ["Nationwide Delivery", "Late Night", "Spicy"],
    menu: [
      {
        id: 301,
        name: "Grilled Chicken",
        price: 6000,
        image: getImg(3),
        category: "Mains",
      },
    ],
  },
  {
    id: 4,
    name: "Amala Sky",
    rating: 4.7,
    reviews: "3.5k",
    deliveryTime: "15-25 min",
    minOrder: 3000,
    image: getImg(4),
    categories: ["Amala"],
    city: "Ibadan",
    address: "Bodija Market Rd",
    openingHours: "9:00 AM - 8:00 PM",
    about: "Fluffy Amala, Gbegiri and Ewedu served piping hot.",
    tags: ["Nationwide Delivery", "Traditional"],
    menu: [
      {
        id: 401,
        name: "Amala & Ewedu",
        price: 2500,
        description: "Fluffy Amala with Gbegiri",
        image: getImg(4),
        category: "Swallows",
      },
    ],
  },
  {
    id: 5,
    name: "Abacha Corner",
    rating: 4.8,
    reviews: "2k",
    deliveryTime: "25-40 min",
    minOrder: 2500,
    image: getImg(5),
    categories: ["Salad", "Abacha", "Traditional"],
    city: "Enugu",
    address: "Independence Layout",
    openingHours: "10:00 AM - 8:00 PM",
    about: "African Salad at its finest.",
    tags: ["Nationwide Delivery", "Light Meal"],
    menu: [
      {
        id: 501,
        name: "Special Abacha",
        price: 3000,
        description: "African Salad with ugba",
        image: getImg(5),
        category: "Mains",
      },
    ],
  },
  {
    id: 6,
    name: "Banga Delight",
    rating: 4.9,
    reviews: "1.1k",
    deliveryTime: "40-50 min",
    minOrder: 6000,
    image: getImg(6),
    categories: ["Soup", "Swallow"],
    city: "Delta",
    address: "Warri Central",
    openingHours: "10:00 AM - 9:00 PM",
    about: "Rich palm nut soup served with your choice of starch or eba.",
    tags: ["Nationwide Delivery", "Traditional"],
    menu: [
      {
        id: 601,
        name: "Banga & Starch",
        price: 6500,
        description: "Rich palm nut soup",
        image: getImg(6),
        category: "Swallows",
      },
    ],
  },
  {
    id: 7,
    name: "Pounded Yam with Egusi Soup",
    rating: 4.5,
    reviews: "1.5k",
    deliveryTime: "30-40 min",
    minOrder: 4000,
    image: getImg(7),
    categories: ["Swallow", "Soup", "Traditional"],
    city: "Benin",
    address: "Airport Rd",
    openingHours: "9:00 AM - 9:00 PM",
    about: "Smooth pounded yam paired with rich, chunky egusi soup.",
    tags: ["Nationwide Delivery", "Heavy Meal"],
    menu: [
      {
        id: 701,
        name: "Pounded Yam & Egusi",
        price: 5000,
        image: getImg(7),
        category: "Swallows",
      },
    ],
  },
  {
    id: 8,
    name: "Owerri Soup",
    rating: 4.7,
    reviews: "950",
    deliveryTime: "35-45 min",
    minOrder: 5500,
    image: getImg(8),
    categories: ["Soup", "Swallow", "Local"],
    city: "Owerri",
    address: "Wetheral Rd",
    openingHours: "10:00 AM - 9:00 PM",
    about: "The legendary Ofe Owerri.",
    tags: ["Nationwide Delivery", "Spicy"],
    menu: [
      {
        id: 801,
        name: "Ofe Owerri",
        price: 7000,
        description: "Assorted meat soup",
        image: getImg(8),
        category: "Soups",
      },
    ],
  },
  {
    id: 9,
    name: "Ofada Rice and Ayamase Stew",
    rating: 4.7,
    reviews: "1.4k",
    deliveryTime: "35-45 min",
    minOrder: 6000,
    image: getImg(9),
    categories: ["Rice"],
    city: "Lagos",
    address: "Ikoyi",
    openingHours: "10:00 AM - 9:00 PM",
    about: "Spicy Ayamase stew with local Ofada rice.",
    tags: ["Nationwide Delivery", "Spicy"],
    menu: [
      {
        id: 901,
        name: "Ofada Rice Special",
        price: 6000,
        description: "Served with spicy Ayamase",
        image: getImg(9),
        category: "Mains",
      },
    ],
  },
  {
    id: 10,
    name: "White Rice and Stew",
    rating: 4.7,
    reviews: "3k",
    deliveryTime: "35-45 min",
    minOrder: 5000,
    image: getImg(10),
    categories: ["Rice"],
    city: "Lagos",
    address: "Yaba",
    openingHours: "9:00 AM - 10:00 PM",
    about: "Classic Nigerian stew served with fluffy white rice.",
    tags: ["Nationwide Delivery", "Classic"],
    menu: [
      {
        id: 1001,
        name: "White Rice & Chicken Stew",
        price: 5000,
        description: "Steaming white rice with stew",
        image: getImg(10),
        category: "Mains",
      },
    ],
  },
  {
    id: 11,
    name: "Fufu with Ogbono Soup",
    rating: 4.7,
    reviews: "3.3k",
    deliveryTime: "35-45 min",
    minOrder: 4500,
    image: getImg(11),
    categories: ["Swallow", "Soup"],
    city: "Lagos",
    address: "Festac",
    openingHours: "10:00 AM - 9:00 PM",
    about: "Draw soup delight served with soft Fufu.",
    tags: ["Nationwide Delivery", "Traditional"],
    menu: [
      {
        id: 1101,
        name: "Fufu & Ogbono",
        price: 4500,
        description: "Smooth fufu with draw soup",
        image: getImg(11),
        category: "Swallows",
      },
    ],
  },
  {
    id: 12,
    name: "Beans and Plantain (Porridge)",
    rating: 4.7,
    reviews: "4k",
    deliveryTime: "35-45 min",
    minOrder: 3500,
    image: getImg(12),
    categories: ["Beans", "Local"],
    city: "Lagos",
    address: "45 Bode Thomas St, Surulere",
    openingHours: "8:00 AM - 9:00 PM",
    about: "Legendary beans pottage that tastes just like home.",
    tags: ["Nationwide Delivery", "Vegetarian Options"],
    menu: [
      {
        id: 1201,
        name: "Beans Porridge & Plantain",
        price: 3500,
        description: "Soft honey beans pottage",
        image: getImg(12),
        category: "Mains",
      },
    ],
  },
  {
    id: 13,
    name: "Smoky Party Jollof",
    rating: 4.9,
    reviews: "5k",
    deliveryTime: "30-45 min",
    minOrder: 4000,
    image: getImg(13),
    categories: ["Rice", "Party"],
    city: "Lagos",
    address: "22 Marina Road, Lagos Island",
    openingHours: "8:00 AM - 10:00 PM",
    about: "The authentic smoky party jollof taste you love.",
    tags: ["Nationwide Delivery", "Bestseller"],
    menu: [
      {
        id: 1301,
        name: "Jollof Rice & Moi Moi",
        price: 4500,
        description: "Smoky jollof served with turkey and moi moi",
        image: getImg(13),
        category: "Mains",
      },
    ],
  },
  {
    id: 14,
    name: "Catfish Pepper Soup",
    rating: 4.8,
    reviews: "1.8k",
    deliveryTime: "40-50 min",
    minOrder: 7000,
    image: getImg(14),
    categories: ["Soup", "Spicy", "Fish"],
    city: "Port Harcourt",
    address: "Peter Odili Rd, Trans Amadi",
    openingHours: "11:00 AM - 11:00 PM",
    about: "Hot and spicy point-and-kill pepper soup.",
    tags: ["Fresh Catch", "Spicy", "Late Night"],
    menu: [
      {
        id: 1401,
        name: "Whole Catfish Pepper Soup",
        price: 8500,
        description: "Spicy broth with fresh catfish and yam",
        image: getImg(14),
        category: "Soups",
      },
    ],
  },
  {
    id: 15,
    name: "Calabar Kitchen (Edikang Ikong)",
    rating: 4.9,
    reviews: "2.2k",
    deliveryTime: "45-55 min",
    minOrder: 6500,
    image: getImg(15),
    categories: ["Soup", "Swallow", "Vegetable"],
    city: "Calabar",
    address: "Marian Road, Calabar",
    openingHours: "9:00 AM - 9:00 PM",
    about: "Nutritious vegetable soup made with pumpkin leaves and waterleaf.",
    tags: ["Traditional", "Healthy", "Nationwide Delivery"],
    menu: [
      {
        id: 1501,
        name: "Edikang Ikong & Fufu",
        price: 7000,
        description: "Rich vegetable soup with assorted meat",
        image: getImg(15),
        category: "Swallows",
      },
    ],
  },
  {
    id: 16,
    name: "Arewa Grill (Tuwo Shinkafa)",
    rating: 4.6,
    reviews: "1.3k",
    deliveryTime: "30-40 min",
    minOrder: 3000,
    image: getImg(16),
    categories: ["Swallow", "Northern"],
    city: "Kano",
    address: "Zoo Road, Kano",
    openingHours: "8:00 AM - 8:00 PM",
    about: "Soft rice flour swallow served with Miyan Kuka.",
    tags: ["Traditional", "Halal"],
    menu: [
      {
        id: 1601,
        name: "Tuwo Shinkafa & Miyan Kuka",
        price: 3500,
        description: "Served with dried okra soup",
        image: getImg(16),
        category: "Swallows",
      },
    ],
  },
  {
    id: 17,
    name: "Nkwobi Palace",
    rating: 4.7,
    reviews: "900",
    deliveryTime: "35-50 min",
    minOrder: 5000,
    image: getImg(17),
    categories: ["Meat", "Local", "Spicy"],
    city: "Enugu",
    address: "Ogui Road, Enugu",
    openingHours: "1:00 PM - 10:00 PM",
    about: "Spicy cow foot delicacy garnished with utazi leaves.",
    tags: ["Evening Special", "Spicy", "Drinks"],
    menu: [
      {
        id: 1701,
        name: "Spicy Nkwobi",
        price: 5000,
        description: "Cow foot in spicy palm oil paste",
        image: getImg(17),
        category: "Mains",
      },
    ],
  },
  {
    id: 18,
    name: "Special Fried Rice",
    rating: 4.6,
    reviews: "3.1k",
    deliveryTime: "25-35 min",
    minOrder: 4500,
    image: getImg(18),
    categories: ["Rice", "Continental"],
    city: "Abuja",
    address: "Gwarinpa Estate",
    openingHours: "9:00 AM - 10:00 PM",
    about: "Richly garnished fried rice with veggies and prawns.",
    tags: ["Nationwide Delivery", "Lunch Special"],
    menu: [
      {
        id: 1801,
        name: "Shrimp Fried Rice",
        price: 5500,
        description: "Loaded with shrimps and diced beef",
        image: getImg(18),
        category: "Mains",
      },
    ],
  },
  {
    id: 19,
    name: "Semo and Efo Riro",
    rating: 4.7,
    reviews: "1.6k",
    deliveryTime: "35-45 min",
    minOrder: 4000,
    image: getImg(19),
    categories: ["Swallow", "Soup", "Vegetable"],
    city: "Lagos",
    address: "Ikeja GRA",
    openingHours: "10:00 AM - 9:00 PM",
    about: "Healthy spinach stew served with smooth Semovita.",
    tags: ["Nationwide Delivery", "Healthy"],
    menu: [
      {
        id: 1901,
        name: "Semo & Efo Riro",
        price: 4500,
        description: "Served with ponmo and fish",
        image: getImg(19),
        category: "Swallows",
      },
    ],
  },
  {
    id: 20,
    name: "Kilishi Hub",
    rating: 4.9,
    reviews: "4.5k",
    deliveryTime: "24-48 hrs",
    minOrder: 5000,
    image: getImg(20),
    categories: ["Snacks", "Meat", "Northern"],
    city: "Abuja",
    address: "Area 1, Garki",
    openingHours: "9:00 AM - 7:00 PM",
    about: "Authentic dried beef jerky spiced with suya pepper.",
    tags: ["Nationwide Delivery", "Snack", "Spicy"],
    menu: [
      {
        id: 2001,
        name: "Beef Kilishi Pack",
        price: 5000,
        description: "Spicy dried meat (Large pack)",
        image: getImg(20),
        category: "Snacks",
      },
    ],
  },
  {
    id: 21,
    name: "9th Mile Okpa",
    rating: 4.8,
    reviews: "1.2k",
    deliveryTime: "20-30 min",
    minOrder: 2000,
    image: getImg(21),
    categories: ["Beans", "Snacks", "Traditional"],
    city: "Enugu",
    address: "New Haven, Enugu",
    openingHours: "7:00 AM - 6:00 PM",
    about: "Hot and spicy Bambara nut pudding wrapped in banana leaves.",
    tags: ["Breakfast", "Light Meal"],
    menu: [
      {
        id: 2101,
        name: "Okpa Di Oku",
        price: 1500,
        description: "Hot Okpa served with pap",
        image: getImg(21),
        category: "Mains",
      },
    ],
  },
  {
    id: 22,
    name: "9th Mile Okpa with Spicy Asun",
    rating: 4.7,
    reviews: "2.8k",
    deliveryTime: "30-40 min",
    minOrder: 5500,
    image: getImg(22),
    categories: ["Grills", "Meat", "Spicy"],
    city: "Lagos",
    address: "Opebi Road, Ikeja",
    openingHours: "4:00 PM - 11:00 PM",
    about: "Peppered smoked goat meat chopped into bite-sized pieces.",
    tags: ["Spicy", "Nightlife", "Outdoor Seating"],
    menu: [
      {
        id: 2201,
        name: "Spicy Asun",
        price: 6000,
        description: "Peppered Goat Meat",
        image: getImg(22),
        category: "Mains",
      },
    ],
  },
  {
    id: 23,
    name: "Smokey jolly rice with Spicy Asun",
    rating: 4.7,
    reviews: "2.9k",
    deliveryTime: "30-40 min",
    minOrder: 5500,
    image: getImg(23),
    categories: ["Rice", "Continental"],
    city: "Lagos",
    address: "Opebi Road, Ikeja",
    openingHours: "4:00 PM - 11:00 PM",
    about: "Peppered smoked goat meat chopped into bite-sized pieces.",
    tags: ["Spicy", "Nightlife", "Outdoor Seating"],
    menu: [
      {
        id: 2201,
        name: "Spicy Asun",
        price: 6000,
        description: "Peppered Goat Meat with Smokey Jolly Rice",
        image: getImg(22),
        category: "Mains",
      },
    ],
  },
];

const uploadData = async () => {
  try {
    console.log("Starting data upload...");
    const batch = writeBatch(db);

    restaurants.forEach((restaurant) => {
      const docRef = doc(db, "restaurants", restaurant.id.toString());
      batch.set(docRef, restaurant);
    });

    await batch.commit();
    console.log("Data upload completed successfully!");
  } catch (error) {
    console.error("Error uploading data: ", error);
  }
};

uploadData();
